### ISSUE TITLE
Bug in DriveStraightDistanceEx 

### ISSUE THREAD

**Issue by tylertian123** [TeamArctos6135/frc-2018#1]
DriveStraightDistanceEx does not function properly. Its error multiplier constant might be too big, resulting in motors' movements being very sudden.

**Comment by tylertian123** [comment]
Code has been added to address this issue. No testing done so far.

**Comment by TeamArctos6135** [comment]
Tuning the error multiplier does not seem to fix the problem.

**Comment by cynicalpillow** [comment]
Forgot to initialize leftSpeed and rightSpeed

**Comment by TeamArctos6135** [comment]
Issue fixed.
