### ISSUE TITLE
Autonomous Changes

### ISSUE THREAD

**Issue by TeamArctos6135** [TeamArctos6135/frc-2018#8]
Delay between auto commands is not enough to fit in Brake sequence.

**Comment by tylertian123** [comment]
Auto turn speed should also be separated from driving speed.<br>
Apart from that, the elevator must also be raised before dropping the Power Cube.

**Comment by tylertian123** [comment]
Code has been added to extend delay and separate variables.

**Comment by tylertian123** [comment]
Code has been added to raise the elevator. Issue is now closed.
